# Generated by Django 5.1.7 on 2025-03-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_format_preference',
            field=models.CharField(choices=[('gregorian', 'Gregorian (Western)'), ('jalali', 'Jalali (Persian)')], default='gregorian', help_text='Choose your preferred date format', max_length=10),
        ),
    ]
