# Generated by Django 5.1.7 on 2025-03-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_user_profiles'),
        ('users', 'create_user_profiles'),
    ]

    operations = [
    ]
