# Generated by Django 4.2.7 on 2025-11-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_merge_0003_create_user_profiles_create_user_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Preferred timezone for displaying dates and resolving alerts",
                max_length=64,
            ),
        ),
    ]
