from django.urls import path
from .views import (
    JiraRuleListView,
    JiraRuleCreateView,
    JiraRuleUpdateView,
    JiraRuleDeleteView,
    SlackRuleListView,
    SlackRuleCreateView,
    SlackRuleUpdateView,
    SlackRuleDeleteView,
    PhoneBookListView,
    PhoneBookCreateView,
    PhoneBookUpdateView,
    PhoneBookDeleteView,
    SmsRuleListView,
    SmsRuleCreateView,
    SmsRuleUpdateView,
    SmsRuleDeleteView,
    jira_admin_view,
    jira_rule_guide_view,
    slack_admin_view,
    slack_admin_guide_view,
    check_slack_template,
    check_sms_template,
    sms_admin_view,
    sms_rule_guide_view,
)

app_name = 'integrations'

urlpatterns = [
    path('jira-rules/', JiraRuleListView.as_view(), name='jira-rule-list'),
    path('jira-rules/new/', JiraRuleCreateView.as_view(), name='jira-rule-create'),
    path('jira-rules/<int:pk>/edit/', JiraRuleUpdateView.as_view(), name='jira-rule-update'),
    path('jira-rules/<int:pk>/delete/', JiraRuleDeleteView.as_view(), name='jira-rule-delete'),
    path('slack-rules/', SlackRuleListView.as_view(), name='slack-rule-list'),
    path('slack-rules/new/', SlackRuleCreateView.as_view(), name='slack-rule-create'),
    path('slack-rules/<int:pk>/edit/', SlackRuleUpdateView.as_view(), name='slack-rule-update'),
    path('slack-rules/<int:pk>/delete/', SlackRuleDeleteView.as_view(), name='slack-rule-delete'),
    path('phonebook/', PhoneBookListView.as_view(), name='phonebook-list'),
    path('phonebook/new/', PhoneBookCreateView.as_view(), name='phonebook-create'),
    path('phonebook/<int:pk>/edit/', PhoneBookUpdateView.as_view(), name='phonebook-update'),
    path('phonebook/<int:pk>/delete/', PhoneBookDeleteView.as_view(), name='phonebook-delete'),
    path('sms-rules/', SmsRuleListView.as_view(), name='sms-rule-list'),
    path('sms-rules/new/', SmsRuleCreateView.as_view(), name='sms-rule-create'),
    path('sms-rules/<int:pk>/edit/', SmsRuleUpdateView.as_view(), name='sms-rule-update'),
    path('sms-rules/<int:pk>/delete/', SmsRuleDeleteView.as_view(), name='sms-rule-delete'),
    path('jira/admin/', jira_admin_view, name='jira-admin'),
    path('slack/admin/', slack_admin_view, name='slack-admin'),
    path('sms/admin/', sms_admin_view, name='sms-admin'),
    path('jira-rules/guide/', jira_rule_guide_view, name='jira-rule-guide'),
    path('slack/admin/guide/', slack_admin_guide_view, name='slack-admin-guide'),
    path('sms-rules/guide/', sms_rule_guide_view, name='sms-rule-guide'),
    path('slack-rules/check-template/', check_slack_template, name='slack-rule-check-template'),
    path('sms-rules/check-template/', check_sms_template, name='sms-rule-check-template'),
]
