services:
  web:
    build: .
    command: /code/entrypoint.sh
    volumes:
      - ./data:/code/db
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=P@ssword
      - DJANGO_SUPERUSER_EMAIL=admin@example.com

