# Generated by Django 4.0 on 2025-03-20 08:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertdocumentation',
            name='description',
            field=tinymce.models.HTMLField(help_text='Description of the alert and problem'),
        ),
    ]
