# Generated by Django 4.0 on 2025-03-20 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='documentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directly_linked_alerts', to='docs.alertdocumentation'),
        ),
        migrations.AddField(
            model_name='alertcomment',
            name='alert_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='alerts.alertgroup'),
        ),
        migrations.AddField(
            model_name='alertcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_comments', to='auth.user'),
        ),
    ]
