# Generated by Django 4.0 on 2025-03-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertinstance',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal Resolution'), ('inferred', 'Inferred Resolution'), ('manual', 'Manual Resolution')], max_length=20, null=True),
        ),
    ]
