# Generated by Django 4.0 on 2025-03-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alertinstance_resolution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='cluster',
            field=models.CharField(blank=True, db_index=True, help_text='Cluster name extracted from labels', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='instance',
            field=models.CharField(blank=True, db_index=True, help_text='Instance address (IP or hostname) extracted from labels', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='job',
            field=models.CharField(blank=True, db_index=True, help_text='Job name extracted from labels', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='namespace',
            field=models.CharField(blank=True, db_index=True, help_text='Namespace extracted from labels for kubernetes alerts', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='service',
            field=models.CharField(blank=True, db_index=True, help_text='Service name extracted from labels', max_length=255, null=True),
        ),
    ]
