# Generated by Django 4.0 on 2025-03-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alertgroup_cluster_alertgroup_instance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertgroup',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='alertgroup',
            name='job',
        ),
        migrations.RemoveField(
            model_name='alertgroup',
            name='namespace',
        ),
        migrations.RemoveField(
            model_name='alertgroup',
            name='service',
        ),
    ]
