# Generated by Django 5.1.7 on 2025-03-26 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alertacknowledgementhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='is_silenced',
            field=models.BooleanField(default=False, help_text='Is this alert group currently silenced by an internal rule?'),
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='silenced_until',
            field=models.DateTimeField(blank=True, help_text='If silenced, when does the current silence rule end?', null=True),
        ),
        migrations.CreateModel(
            name='SilenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchers', models.JSONField(help_text='Labels to match exactly. E.g., {"job": "node_exporter", "instance": "server1"}')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_silence_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Silence Rule',
                'verbose_name_plural': 'Silence Rules',
                'ordering': ['-starts_at'],
            },
        ),
    ]
