# Generated by Django 4.0 on 2025-04-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alertgroup_is_silenced_alertgroup_silenced_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraRuleMatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identifier for this matcher set', max_length=100)),
                ('match_criteria', models.JSONField(default=dict, help_text='JSON object where keys are label names and values are exact strings or regex patterns to match. Example: {"severity": "critical", "cluster": "prod-us-east-.*"}')),
                ('is_regex', models.BooleanField(default=False, help_text='Set to True if any values in match_criteria are regex patterns.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='jira_issue_key',
            field=models.CharField(blank=True, db_index=True, help_text='The key of the Jira issue associated with this alert group (e.g., PROJECT-123).', max_length=50, null=True, verbose_name='Jira Issue Key'),
        ),
        migrations.CreateModel(
            name='JiraIntegrationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('jira_project_key', models.CharField(help_text='Target Jira project key (e.g., OPS)', max_length=50)),
                ('jira_issue_type', models.CharField(help_text='Target Jira issue type (e.g., Bug, Task)', max_length=50)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matchers', models.ManyToManyField(help_text="Select one or more matchers. The rule applies if ALL selected matchers match the alert's labels.", related_name='rules', to='alerts.JiraRuleMatcher')),
            ],
            options={
                'verbose_name': 'Jira Integration Rule',
                'verbose_name_plural': 'Jira Integration Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
