# Generated by Django 5.1.7 on 2025-04-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_jirarulematcher_alertgroup_jira_issue_key_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JiraIntegrationRule',
        ),
        migrations.DeleteModel(
            name='JiraRuleMatcher',
        ),
    ]
