# Generated by Django 3.2.20 on 2025-05-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_delete_jiraintegrationrule_delete_jirarulematcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='source',
            field=models.CharField(blank=True, db_index=True, help_text='Identifier for the source Alertmanager instance', max_length=100, null=True),
        ),
    ]
