# Generated by Django 3.2.20 on 2025-07-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alertgroup_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertinstance',
            name='started_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
