# Generated by Django 3.2.20 on 2025-08-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackIntegrationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first.')),
                ('match_criteria', models.JSONField(default=dict, help_text='JSON object defining label match criteria. E.g., {"job": "node", "severity": "critical"}')),
                ('slack_channel', models.CharField(help_text='Destination Slack channel (e.g., #critical-alerts)', max_length=100)),
                ('message_template', models.TextField(blank=True, help_text='Template for Slack message. Uses Django template syntax.')),
                ('resolved_message_template', models.TextField(blank=True, help_text='Template used when an alert is resolved. Uses Django template syntax.')),
            ],
            options={
                'verbose_name': 'Slack Integration Rule',
                'verbose_name_plural': 'Slack Integration Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
