# Generated by Django 4.0 on 2025-04-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraintegrationrule',
            name='matchers',
            field=models.ManyToManyField(help_text="Select one or more matchers. The rule applies if ALL selected matchers match the alert's labels.", related_name='rules', to='integrations.JiraRuleMatcher'),
        ),
    ]
