# Generated by Django 3.2.20 on 2025-08-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_slackintegrationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackintegrationrule',
            name='resolved_message_template',
            field=models.TextField(blank=True, help_text='Template used when an alert is resolved. Uses Django template syntax.'),
        ),
    ]