# Generated by AI on 2025-??
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_slackintegrationrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, db_index=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='SmsIntegrationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first.')),
                ('match_criteria', models.JSONField(default=dict, help_text='JSON object to match AlertGroup attributes. Use "labels__<key>" for label matching and regular field names or lookups (e.g., "source", "jira_issue_key__isnull") for AlertGroup properties.')),
                ('recipients', models.CharField(blank=True, help_text='Comma-separated list of recipient names defined in PhoneBook.', max_length=255)),
                ('use_sms_annotation', models.BooleanField(default=False, help_text="If true, resolve recipients from alert annotations['sms'] instead of rule recipients.")),
                ('firing_template', models.TextField(help_text='Template for SMS message when alert is firing.')),
                ('resolved_template', models.TextField(blank=True, help_text='Optional template for SMS message when alert is resolved. If blank, no message is sent on resolve.')),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'verbose_name': 'SMS Integration Rule',
                'verbose_name_plural': 'SMS Integration Rules',
            },
        ),
    ]
