# Generated by Django 3.2.20 on 2025-04-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_jiraintegrationrule_matchers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jiraintegrationrule',
            name='matchers',
        ),
        migrations.AddField(
            model_name='jiraintegrationrule',
            name='match_criteria',
            field=models.JSONField(default=dict, help_text='JSON object defining label match criteria. E.g., {"job": "node", "severity": "critical"}'),
        ),
        migrations.DeleteModel(
            name='JiraRuleMatcher',
        ),
    ]
