# Generated by Django 4.2.21 on 2025-08-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_add_resolved_message_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackintegrationrule',
            name='match_criteria',
            field=models.JSONField(default=dict, help_text='JSON object to match alerts. Use "labels" for alert labels and "fields" for alert group properties (e.g., source, acknowledged).'),
        ),
    ]
