# Generated by Django 3.2.20 on 2025-04-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20250426_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraintegrationrule',
            name='jira_description_template',
            field=models.TextField(blank=True, default='Firing alert details:\nLabels:\n{% for key, value in labels.items() %}  {{ key }}: {{ value }}\n{% endfor %}\nAnnotations:\n{% for key, value in annotations.items() %}  {{ key }}: {{ value }}\n{% endfor %}', help_text='Template for the Jira issue description. Uses Django template syntax. Available context: labels (dict), annotations (dict), alertname, status, etc. See documentation for full context.'),
        ),
        migrations.AddField(
            model_name='jiraintegrationrule',
            name='jira_title_template',
            field=models.TextField(blank=True, default='Alert: {{ alertname }} for {{ job }}', help_text="Template for the Jira issue title. Use {{ label_name }} or {{ annotation_name }}. Default: 'Alert: {{ alertname }} for {{ job }}'"),
        ),
        migrations.AddField(
            model_name='jiraintegrationrule',
            name='jira_update_comment_template',
            field=models.TextField(blank=True, default="Alert status changed to {{ status }}. \n{% if status == 'firing' %}Labels:\n{% for key, value in labels.items() %}  {{ key }}: {{ value }}\n{% endfor %}{% endif %}", help_text='Template for the comment added when an existing Jira issue is updated (e.g., alert resolved or re-fired). Uses Django template syntax.'),
        ),
    ]
