# Generated by Django 4.2.7 on 2025-10-12 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0011_alter_alertinstance_started_at"),
        ("integrations", "0003_phonebook_smsintegrationrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("recipients", models.JSONField(default=list)),
                ("message", models.TextField()),
                ("delivery_method", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("queued", "Queued"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider_response", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "alert_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_message_logs",
                        to="alerts.alertgroup",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_logs",
                        to="integrations.smsintegrationrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
