# Generated by Django 3.2.20 on 2025-04-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_auto_20250426_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jiraintegrationrule',
            name='description',
        ),
    ]
