# Generated by Django 4.2.7 on 2025-10-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_smsmessagelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonebook",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
