# Generated by Django 3.2.20 on 2025-08-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_slackintegrationrule_match_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackintegrationrule',
            name='match_criteria',
            field=models.JSONField(default=dict, help_text='JSON object to match AlertGroup attributes. Use "labels__<key>" for label matching and regular field names or lookups (e.g., "source", "jira_issue_key__isnull") for AlertGroup properties.'),
        ),
    ]
