# Generated by Django 4.2.7 on 2025-10-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_phonebook_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonebook",
            name="contact_type",
            field=models.CharField(
                choices=[("internal", "Internal Users"), ("oms", "OMS Customers")],
                db_index=True,
                default="internal",
                max_length=20,
            ),
        ),
    ]
