# Generated by Django 3.2.20 on 2025-04-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_remove_jiraintegrationrule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraintegrationrule',
            name='assignee',
            field=models.CharField(blank=True, help_text='Jira username to assign the issue to (leave blank for no assignment)', max_length=100),
        ),
    ]
