# Generated by Django 3.2.20 on 2025-08-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_alter_slackintegrationrule_match_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraintegrationrule',
            name='match_criteria',
            field=models.JSONField(default=dict, help_text='JSON object to match AlertGroup attributes. Use "labels__<key>" for label matching and regular field names or lookups (e.g., "source", "jira_issue_key__isnull") for AlertGroup properties.'),
        ),
        migrations.AlterField(
            model_name='slackintegrationrule',
            name='slack_channel',
            field=models.CharField(blank=True, help_text='Destination Slack channel (e.g., #critical-alerts). Leave empty to use labels.channel or default.', max_length=100),
        ),
    ]
