# Generated by Django 3.2.20 on 2025-04-28 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0006_jiraintegrationrule_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraintegrationrule',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users who should be added as watchers to the Jira issue', related_name='jira_watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
